version: '3.2'
services:
  flask:
    build: .
    image: kyontan/netcon-score-server:vm-management-service
    restart: always
    ports:
      # flask app (vmms)
      - 127.0.0.1:8950:81
      # nginx (proxy)
      - 127.0.0.1:8951:80
    network_mode: host
